# Generated by Django 3.2.18 on 2023-03-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0002_alter_loan_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
