# Generated by Django 3.2.18 on 2023-03-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0003_alter_loan_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
