# Generated by Django 3.2.18 on 2023-03-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dependents',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=(0, '0')),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.CharField(choices=[('graduated', 'Graduated'), ('not_graduated', 'Not Graduated')], default=('graduated', 'Graduated'), max_length=13),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=('male', 'Male'), max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='married',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=('yes', 'Yes'), max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='property_area',
            field=models.CharField(choices=[('urban', 'Urban'), ('rural', 'Rural')], default=('urban', 'Urban'), max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='self_employed',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=('yes', 'Yes'), max_length=3),
        ),
    ]
